### ISSUE TITLE
Regarding Gitbook Display of flowchart

### ISSUE THREAD

**Issue by madhuakula** [nsdont/gitbook-plugin-new-flowchart#4]
- I have installed using `sudo npm install gitbook-plugin-new-flowchart -g`
- Then I added a file called `book.json` with the below content

```
{
  "plugins": ["new-flowchart"]
}
```
- Then I installed using gitbook `gitbook install`
- Then I started the server using `gitbook serve`
- I don't see the flowchart in browser, I can only see empty screen.

**Comment by madhuakula** [comment]
any update??

**Comment by nsdont** [comment]
Sorry, i no see this notify.

You can show the console log? I want to know load plugin success.

I start new book for test, don't need install -g. only do write book.json and `gitbook install`. I will update README.md .

my console log:

```
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: loading book configuration....OK
info: load plugin gitbook-plugin-new-flowchart ....OK
info: load plugin gitbook-plugin-highlight ....OK
info: load plugin gitbook-plugin-search ....OK
info: load plugin gitbook-plugin-sharing ....OK
info: load plugin gitbook-plugin-fontsettings ....OK
info: load plugin gitbook-plugin-livereload ....OK
info: >> 6 plugins loaded
info: start generation with website generator
info: clean website generator
info: OK
info: generation is finished

Starting server ...
Serving book on http://localhost:4000
```

**Comment by madhuakula** [comment]
It's perfectly generating in the console. But when I see in the Gitbook pages it's empty space, there is no image (or) diagram.

**Comment by nsdont** [comment]
I update the examples, you can check it.
<img width="788" alt="2016-06-03 08 15 23" src="https://cloud.githubusercontent.com/assets/1725434/15765099/59fe2f7c-2963-11e6-88fa-1acab0ff835f.png">

**Comment by madhuakula** [comment]
![selection_021](https://cloud.githubusercontent.com/assets/6764192/15769109/785589f4-2975-11e6-8fe3-3f0ceb3ad945.png)

I don't see any output in the browser. Looks like something broken. Please check the screenshot.

**Comment by nsdont** [comment]
You can visit this [link](http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.2/raphael-min.js)?
This is raphael cdn.

**Comment by madhuakula** [comment]
How to fix this?

**Comment by nsdont** [comment]
Fastest way: change cdn url. Source file `node_modules/gitbook-plugin-new-flowchart/index.js`, replace `<script src='//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.2/raphael-min.js'></script>` to your available cdn url.

For new version, i will use local file.

**Comment by madhuakula** [comment]
I tried giving the local path by downloading the raphael file. If you don't mind could you please make a docker or some thing to test?

Thank you so much for the responses :+1:
